name = "Retrosheet"
uuid = "c739b1be-4162-4ae4-b32d-1e6905ec263e"
authors = ["Neel Smith <dnsmith.neel@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
DocStringExtensions = "0.8"
Documenter = "0.26"